### ISSUE TITLE
Error with healthcare pipeline

### ISSUE THREAD

**Issue by KellySKwon** [hatrungduc/spark-nlp-starter-scripts#2]
Hi Devin - I ran the updated script from yesterday, but now need help with this issue:

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-6-d2e39754d773> in <module>
      9         #.setInputCols(["document"])\
     10         #.setOutputCol("sentence")
---> 11 sentenceDetector = SentenceDetectorDLModel.pretrained("sentence_detector_dl_healthcare","en","clinical/models")\
     12         .setInputCols(["document"])\
     13         .setOutputCol("sentence")

~/opt/anaconda3/lib/python3.8/site-packages/sparknlp/annotator.py in pretrained(name, lang, remote_loc)
   3119     def pretrained(name="sentence_detector_dl", lang="en", remote_loc=None):
   3120         from sparknlp.pretrained import ResourceDownloader
-> 3121         return ResourceDownloader.downloadModel(SentenceDetectorDLModel, name, lang, remote_loc)
   3122 
   3123 

~/opt/anaconda3/lib/python3.8/site-packages/sparknlp/pretrained.py in downloadModel(reader, name, language, remote_loc, j_dwn)
     45     def downloadModel(reader, name, language, remote_loc=None, j_dwn='PythonResourceDownloader'):
     46         print(name + " download started this may take some time.")
---> 47         file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
     48         if file_size == "-1":
     49             print("Can not find the model to download please check the name!")

~/opt/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py in __init__(self, name, language, remote_loc)
    204 class _GetResourceSize(ExtendedJavaWrapper):
    205     def __init__(self, name, language, remote_loc):
--> 206         super(_GetResourceSize, self).__init__(
    207             "com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize", name, language, remote_loc)
    208 

~/opt/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py in __init__(self, java_obj, *args)
    142         super(ExtendedJavaWrapper, self).__init__(java_obj)
    143         self.sc = SparkContext._active_spark_context
--> 144         self._java_obj = self.new_java_obj(java_obj, *args)
    145         self.java_obj = self._java_obj
    146 

~/opt/anaconda3/lib/python3.8/site-packages/sparknlp/internal.py in new_java_obj(self, java_class, *args)
    152 
    153     def new_java_obj(self, java_class, *args):
--> 154         return self._new_java_obj(java_class, *args)
    155 
    156     def new_java_array(self, pylist, java_class):

~/opt/anaconda3/lib/python3.8/site-packages/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     67             java_obj = getattr(java_obj, name)
     68         java_args = [_py2java(sc, arg) for arg in args]
---> 69         return java_obj(*java_args)
     70 
     71     @staticmethod

~/opt/anaconda3/lib/python3.8/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

~/opt/anaconda3/lib/python3.8/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
    126     def deco(*a, **kw):
    127         try:
--> 128             return f(*a, **kw)
    129         except py4j.protocol.Py4JJavaError as e:
    130             converted = convert_exception(e.java_exception)

~/opt/anaconda3/lib/python3.8/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: DA6V9X53ZDK9R1Z6; S3 Extended Request ID: M3m0sRb7IkM0WQxxP4myXJY1wZO4QuXetnvdT3f/07pBK8V6s5RLEsZQ6tLjKJome855Xsk58WM=), S3 Extended Request ID: M3m0sRb7IkM0WQxxP4myXJY1wZO4QuXetnvdT3f/07pBK8V6s5RLEsZQ6tLjKJome855Xsk58WM=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1467)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1326)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:84)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:96)
	at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:174)
	at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:423)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:521)
	at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DevinTDHa** [comment]
Hi @KellySKwon,

To resolve the issue, i have some questions:

1. Was the authentication cell run before running? And have you made sure the licenses with the exact names of `spark_nlp_for_healthcare.json` and `spark_ocr.json` are in the `macOS-catalina` folder?
2. Which Pipeline are you running?

I am testing it on a virtualized solution but I can't reproduce it at the moment.
Thanks!
Devin

**Comment by KellySKwon** [comment]
Yes authentication cell is running. This error comes when running the healthcare pipeline at "sentence_detector_dl". Btw, this was the same error I had before on Sagemaker. Alberto mentioned this could be an issue with my license? 

import sparknlp
import sparknlp_jsl
from sparknlp.base import *
from sparknlp.util import *
from sparknlp.annotator import *
from sparknlp_jsl.annotator import *
from sparknlp.pretrained import ResourceDownloader

from pyspark.sql import functions as F
from pyspark.ml import Pipeline, PipelineModel

# Annotator that transforms a text column from dataframe into an Annotation ready for NLP
documentAssembler = DocumentAssembler()\
        .setInputCol("text")\
        .setOutputCol("document")

# Sentence Detector annotator, processes various sentences per line

#sentenceDetector = SentenceDetector()\
        #.setInputCols(["document"])\
        #.setOutputCol("sentence")
sentenceDetector = SentenceDetectorDLModel.pretrained("sentence_detector_dl_healthcare","en","clinical/models")\
        .setInputCols(["document"])\
        .setOutputCol("sentence")
 
# Tokenizer splits words in a relevant format for NLP
tokenizer = Tokenizer()\
        .setInputCols(["sentence"])\
        .setOutputCol("token")

# Clinical word embeddings trained on PubMED dataset
word_embeddings = WordEmbeddingsModel.pretrained("embeddings_clinical","en","clinical/models")\
        .setInputCols(["sentence","token"])\
        .setOutputCol("embeddings")

# NER model trained on i2b2 (sampled from MIMIC) dataset
clinical_ner = MedicalNerModel.pretrained("ner_clinical_large","en","clinical/models")\
        .setInputCols(["sentence","token","embeddings"])\
        .setOutputCol("ner")

ner_converter = NerConverter()\
        .setInputCols(["sentence","token","ner"])\
        .setOutputCol("ner_chunk")

nlpPipeline = Pipeline(stages=[
        documentAssembler,
        sentenceDetector,
        tokenizer,
        word_embeddings,
        clinical_ner,
        ner_converter])


data = spark.createDataFrame([["""The human KCNJ9 (Kir 3.3, GIRK3) is a member of the G-protein-activated inwardly rectifying potassium (GIRK) channel family. Here we describe the genomicorganization of the KCNJ9 locus on chromosome 1q21-23 as a candidate gene forType II diabetes mellitus in the Pima Indian population. The gene spansapproximately 7.6 kb and contains one noncoding and two coding exons separated byapproximately 2.2 and approximately 2.6 kb introns, respectively. We identified14 single nucleotide polymorphisms (SNPs), including one that predicts aVal366Ala substitution, and an 8 base-pair (bp) insertion/deletion. Ourexpression studies revealed the presence of the transcript in various humantissues including pancreas, and two major insulin-responsive tissues: fat andskeletal muscle. The characterization of the KCNJ9 gene should facilitate furtherstudies on the function of the KCNJ9 protein and allow evaluation of thepotential role of the locus in Type II diabetes."
"""]]).toDF("text")

model = nlpPipeline.fit(data)
result = model.transforme(data)
result.select("ner_chunk").show()

**Comment by C-K-Loan** [comment]
Hi @KellySKwon  your error messages imply something is wrong with your authentification.

Please keep in mind, if you already started a spark context and then try authenticate afterwards, you still get these errors.
You avoid this, please restart the python Kernel and make sure Jars are available and also auth cells are run.
 
Please keep us updated, 
thanks a lot

**Comment by KellySKwon** [comment]
Hello. The initial setup was run only once. I restart the kernel, run the authentication again. I'm still getting this error. Not sure what I'm doing wrong.
